language: node_js

node_js:
  - "stable"

install:
  - cd flexienok
  - npm install
  - npm run build

deploy:
  local_dir: ./dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
 