language: node_js
node_js:
- node
cache: npm
before_script:
- cd flexienok
- npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
  api_key:
    secure: fDDSoFqLp62jtxFNBFra4ZTE/RTTZYHfQzmDslR2hD2/37OEcGl1RLrJKTShT9k3wZpWCi+wa1p62/RcTrSdOa6Ocg1C/ZCU5o5aXkEZhk6dRksoS2DLEY1ameONAi9eQ34dsSjv4q+0CrGTzzbbFAzuaOZzLxQhS613W1KVqSbHKZ6uglsEeJbK5FAu4S7deSztuqOdEpTuEMQCq5sYsXEoTDYykdASw6BJU3iicR6KvDPhM8+Qf8kRIFIwAECtLSBCnEqG5jEXC7vQcHFZ4/10pf5UbQcW/42/QTj5gtnWuUffijQrklXcBOg61WjxicQfwwpJrDkuqeqnUA/EZVypCg1HU+Ix/ilW9WwmTm+Vx3ozQEds9bMGAkWG79nUj25mEOPTFPOaXz04Ubvs7SsxINNp6eBPmw4KVlUh/EdhHw03Qj+XrfQtEAMMwiu8Tz8uZvoNWW1HRS5nzXfwJqGDAC5vrlC2UkN4CcMvntvn3m0ejdTNHFamHkBDlk6aRxsRXgf+6uSafSpcG03I7xDurYBtIy9UaZNvE8dbzwT4qhQCJ2qH+qvjW2LDp4zTFJuJ0gnVcgIcfc6y1l4Sgs7PgtDvc8C9xI80FRkzURVlUcc324RLucI0B+bWHKIT1454DvunX/PnZ/NDULBCBDwSdfuSAXOvFkzK9QVX70Y=
env:
  global:
  - secure: W6Beak0BBIkh4p6LhJAXv3b+Y3OM5R+c/4VXur4Nfm0D0V6Q/HyuhwWzCkOoiGWxuZZpR6VYReE7ZhyrAXBYvHdquDvhG7+BqFgazWA5RebMJ0R18BUrZrz6uEe/Kg4lbtjaub+5gV6tTh+v+ZdpkBO6pu3ylIr9xvew5C/NnTFUUMxkP72xsShA1x3wqEAnjNlSMdQ5ifWoFt/3DCLl9q0UqmASpsl6KcCYfOnC4fAfPZEwdh0rIU4xpo4qy5ANoLnHB3ekPQvSxkfZc3wO3i5yo3/ggqxMA5hrmFRVjAMjoS+ayblAkZhnaMwkKDMjA5mK0SdCzaE9kCChbMjsGWo/OLC3Afqmmb9REPop8TFdSJ1H1maL9fnsfdz2wQWbYCxZPKlJfpq1OrYqVD2D2+T/NOp7HJESKi6jEKxPhJWCKDCjBfCTAHEO3p8nMrX5FYJ+nV+SupVwq+HlFIV88xnJIOdebbtfAQhKzp8P2s3mS2xJ7rAo4/3JWs8tg8S2kxhVkLHAsDx/E7injmQ9WN6WV+7j6B+qbPhpqMsBaxOzm8BPCEwDHBcibKrJRJS9ppue6n6n1SnQXWnkeZXY4yXI4i8cXTNhMzsiDwkqFqZ5o1J+t1FmJLaJ54MfBuDdSZCYzlHLzFC00pbb6xll9bZp6FfO2MeAxcXsal28EXA=
  - secure: c1zqh1SjwiFKJuO7SAPPBC/rZtSLc2WkAYz+qbH0p+S5mHE7p8AS5Cb/z8t+syN1yjh2ptHodgc3Vo42lmpW5z3o/dXVP9VudhVUYDNJl+J0uyV6KExr5oh87vrKp28XV9e0BaN0DgvoBV8p8/o/gJB9A9jHrf8g2gZ2RCBzizUqEm6ryTRVYeUPAglsstDypXJrYnQep68iNGTmaX8OuERsQu2dovyrDjXMpWS0Gz506v+eeKudSANjtcC4hXuiMDZzwSuloK5tczN+pCKi6xYC3HpNKlr1YYvUQBL1VDdASxDkBpblhlojfovhnUCNTe/Ouql0XZKRNTQi5kCrW2LAhqHInaHxwFzgaZd+S45cS0AKSOx/bMSzFlF85/txX8tSVbqRAL9z0eXiCuuze05TLsSum3nJfqHpgEhr5rwBbNOKYWqV2pVSbk62k1eD4Nt6q/qaMRepdAflEP6nI7tUX+yiCz3PH08vWPcy5K+Fm2/kp7phSTQIkno3AkpYcZboOR3+YnPMvzd9kvk8iOmOoxWeBJM+S3f7TzX5k86ihozvKo6nQEsJnZ/TPBekqZ5p4RY8hOy9NcrAonC8nt0ZRai8vowfqUimor3zT9AnK1AWaQ3XtgT2YGQL11uviBK3m7E9e4w/zmQtgMUOg4RnJMnp88QZUWntXLSAGCM=
