language: node_js
node_js:
- stable
install:
- cd flexienok
- npm install
- npm run build
deploy:
  local_dir: "./dist"
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
env:
  global:
  - secure: uTg7/x93r74GZO0MfJRB7x9w57hRAKCMqbvLdUFxnq9FWlwhcaLGqadzjvIWHAQ9S0l4fRuec7EzopTvrkE7gsF64C36wYvmXXLBZuqERkNYD2tWRwxeYu4Jz3gTE7mTXvBNSSXJ9XkP9Ig3Yfo9Iw4W+4bnDKF9latxdH9bzFBBdrVeUbg5g1RV8G4TnDN9V152og6QwbXLHNmP4yvNu0YBI+OeP5KIZOI5r0eHyHuNAU1Ssrt8P9473b9USNsReV9gRwiobFC6XxCsQboTfJ5QKz45fsalXfxhmMlHE5oZp/30bBf4zJw4b1qP154wOUOs9vXfqmG7nGtxict6FP7zG5v/3Mm3dFr5VE+k/JzMxHrl74ir91BscsyxvCGrrJidxeEePYzrbhukcBj+4tdx8e3AGBxP0pnAGmquItxpOQMM24KJn951cUA7TeXODKYjflTgh0dfdovTjPlpkOiotEoUNJ2upvUOofHtVarhEz0bN/SdGW0UDhFaqVcy6azjcHAzrxAai+eVYY7rJdnu0SRTDj2BpptP91njP8Eo0OL4YLNDruRDu6HbloNh8oRDuTSUSVvW8ZFBzFBrGHZW/uAOrZGIh0qb8pAGbDxG+uGS5B0QdAPve8kmKG1jBWYOUIUJREbYJ5I4raM0RsW1j0dpnouruRw875wFEqE=
  - secure: g7krQ8580dptefdcZKI9Ju+X9y8rWs/86LZv7whvPtqmVZAOoFoP617Vt2ZpHbZ+nvqd8Ap6x3QbOn3eWhwTo7Cix8/szl8F9w1GXSwIK+a+NWE0F/gdnFo+bmNz4YLviom+vf2n69zLr71P0qPqN/HLqhf4at/xwl34CIaYEqbtvQbFU3F5q7GSsK/pwAAsi0bq0JhZcrWRd0w+V13OFWmY/6TK1K5HUd3zt2sSTWusQsZFVljjyipSxLPNp7d+f2PLUQCTRv/bIjNm60y41qUvKVMjAOO2Mw8IcF5uqAOPKywqCZeBDODwc4vIoVaASslMfshJ/OWa4eiImSqkTKknI18xisdXrl5L2nB5M7ddpRl4pRYDrj+rv7y/zxSOIGJ05/rMXFEXC47z88NEgQ8G5+p2+ZEDG6O/gP+k7coUYpLHIutP34BLARtNJH/NnCJA3DjsYk5Bu9qF7rzv51Wn5GpR0a9Ab0ZBMmOKbJMh5wn8KtkEkAlEj5KMmDw+LD1/MfB44KmGfF6IJTvExZLeuXl/UDhNVbg0Uw99MSccBnShBFv6/PnjrIA1D4Nwz6/evUPb1mI36EgyvG8TG++PLKRL4Yb//njI3QZS/vPOfQngbdjLgtnzGx0THCxCwUhQLZXLfjQ8+vhuXag2DuQkPv06RxmfX9JA+zpZuX0=
  - secure: HU5MkywfwZpdK4dHvB7cXIMmv9cD0OihruJzDSpBZJqV2YLbWKrak7XlLI1NMXhZZzBc+BtlFSi58cLAvEFMGTkz6bRtHTuvuUn/IC2EcwoD83TcDVYiuOQDn6HB2Wd4J40y5zCzJ2L1CHMPNyvb72mg/MnCXrqA/nFUbfH0TJqvG8I5TfacoV6RHPnWxWqZ8rQpYy1UvFMLXn6YtxEGyL7oaP++UNgEo4iTc8jL4BdJRm4CvhyyBG5S4rQ9et6upu3312Wv4/MeDuUBLjYwTvwmcBWKfmJI++by536ONLo3Dm4T/d3g+5xy6aoqZc2XHFTZ3ifeBtWmA8U1ApoGecLswlXGG++wnXdLmmlBsZrBqVgwjv8XmJsnluScFe8lMmjIz3nljtzljozcQCJQfrp5TgJV56m9Hseo55KCvxtjDVZ73FV50MNLQ2knbf/nTFxmCTJ3fSOvb8un+DuKN89m1Dos4awDjUJ/2jRNBPPcA8XxCnn9nvFD2W+h4b7Mgep43WjASVtrbk2PpCt0gCLkR2aJRRPsgDe4lBCrW0pNqy7CphCE36md5Y/tvUdxLjdqYtv3KtMXv9VSM6vunrBnDz9q7QBtSQaldzNDA7+BuMB6Gn373b2+O+IkF58A4dAWo4rj4OPKVUSDvEVObFlTFW1UL7mEyWboW2Wz1Ew=
